server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: salesmanagement-service
          uri:  http://localhost:8081/
          predicates:
            - Path=/api/customer/**
