server:
  port: 8080

security:
  jwt:
    expirationMinutes: 30
    secretKey: TUkgQ09OVFJBU0XDkUEgRVMgTVVZIFNFR1VSQSBFUyBEQU5JRUwxMjAyIGx1ZGExMjAyIGphamE=

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SALESMANAGEMENT-SERVICE
          uri: lb://SALESMANAGEMENT-SERVICE
          predicates:
            - Path=/sm/**
            
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka