server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: salesmanagement-service
        uri: lb://salesmanagement-service
        predicates:
        - Path=/salesmanagement-service/**
        filters:
          - StripPrefix=1

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka           


