server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: SALESMANAGEMENT-SERVICE
            uri: lb://SALESMANAGEMENT-SERVICE
            predicates:
              - Path=/api/**

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8088/eureka