server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: salesmanagement-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka         
