server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        - id: salesmanagement-service
          uri:  http://localhost:8081
          predicates:
            - Path=/api/customer/**
