server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_business_management_platform?currentSchema=sc_business_management_platform&ssl=false
    username: postgres
    password: 6012
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
