server:
  port: 8082

service:
  security:
    user:
      name: daniel
      password: $2a$10$kHTLI/iNlhV4JkFx7ZC7yeA5S7.w8BLz5BeSRFONMT3gC39owsdkC

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_business_management_platform?currentSchema=sc_business_management_platform&ssl=false
    username: postgres
    password: 6012
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8099

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true