spring:
  application:
    name: accesscontrol-service

  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: s3cr3t

logging:
  level:
    org.springframework.security.web: DEBUG