spring:
  application:
    name: registry-service
  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: s3cr3t

logging:
  level:
    org.eclipse.jgit: DEBUG