spring:
  application:
    name: salesmanagement-service

  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: s3cr3t

service:
  security:
    user:
      name: daniel
      password: $2a$10$kHTLI/iNlhV4JkFx7ZC7yeA5S7.w8BLz5BeSRFONMT3gC39owsdkC

logging:
  level:
    org.springframework.security.web: DEBUG
