spring:
  application:
    name: map-service
  config:
    import:
      - optional:configserver:http://localhost:8080
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
