server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanielPalacioss/enterprise_resource_planning_back.git
          searchPaths: Config/config-data
          username : ${GIT_USER}
          password : ${GIT_PASSWORD}
  security:
    user:
      name : root
      password : s3cr3t
logging:
  level:
    org.eclipse.jgit: DEBUG
